services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn loginproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: loginproject.settings
      - key: PYTHON_VERSION
        value: 3.10
